node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build && push image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
        script {
            dir('jenkins-slave/') {
                app = docker.build("jenkins-slave")
                docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("latest")  
                }
            }
        }
    }
}
